" grafana-dark.vim -- Grafana Dark
" Generated by tools/generate.py from palette.toml. Do not edit.
" https://github.com/ymotongpoo/grafana-color-scheme
" SPDX-License-Identifier: Apache-2.0
"
" Truecolor is not enabled here on purpose. Add to your own config:
"   set termguicolors
" and inside tmux (3.2+):
"   set -as terminal-features ",*:RGB"

highlight clear
if exists('syntax_on')
  syntax reset
endif

set background=dark
let g:colors_name = 'grafana-dark'

" Opt out of italics if your terminal renders them as reverse video.
let s:italic = get(g:, 'grafana_italic', 1) ? 'italic' : 'NONE'
let s:bold = get(g:, 'grafana_bold', 1) ? 'bold' : 'NONE'

" Palette: [gui, cterm]
let s:crust       = ['#181411', '233']
let s:mantle      = ['#1e1916', '234']
let s:base        = ['#241f1c', '234']
let s:surface0    = ['#2c2622', '235']
let s:surface1    = ['#362f2a', '236']
let s:surface2    = ['#423932', '237']
let s:bright      = ['#cbc3ba', '251']
let s:fg          = ['#b9b1a9', '249']
let s:subtext     = ['#8d8279', '102']
let s:faint       = ['#786d63', '242']
let s:orange      = ['#c18c68', '137']
let s:amber       = ['#b4a075', '144']
let s:yellow      = ['#acaa70', '144']
let s:green       = ['#89a17e', '108']
let s:light_green = ['#79a08a', '108']
let s:light_blue  = ['#789fa6', '109']
let s:blue        = ['#8198b5', '67']
let s:indigo      = ['#8d86b1', '103']
let s:purple      = ['#ad8eaf', '139']
let s:pink        = ['#b77f94', '138']
let s:none = ['NONE', 'NONE']

function! s:hi(group, fg, bg, attr, sp) abort
  let l:cmd = 'highlight ' . a:group
  let l:cmd .= ' guifg=' . a:fg[0] . ' ctermfg=' . a:fg[1]
  let l:cmd .= ' guibg=' . a:bg[0] . ' ctermbg=' . a:bg[1]
  let l:cmd .= " gui=" . a:attr
  " undercurl is unavailable in most terminals; fall back to underline.
  let l:cmd .= ' cterm=' . substitute(a:attr, 'undercurl', 'underline', 'g')
  if a:sp !=# ''
    let l:cmd .= ' guisp=' . a:sp
  endif
  execute l:cmd
endfunction

call s:hi('Normal', s:fg, s:base, 'NONE', '')
call s:hi('NormalNC', s:fg, s:base, 'NONE', '')
call s:hi('NormalFloat', s:fg, s:mantle, 'NONE', '')
call s:hi('FloatBorder', s:surface2, s:mantle, 'NONE', '')
call s:hi('FloatTitle', s:orange, s:mantle, s:bold, '')
call s:hi('Cursor', s:base, s:orange, 'NONE', '')
call s:hi('lCursor', s:base, s:orange, 'NONE', '')
call s:hi('CursorLine', s:none, s:surface0, 'NONE', '')
call s:hi('CursorColumn', s:none, s:surface0, 'NONE', '')
call s:hi('CursorLineNr', s:fg, s:surface0, s:bold, '')
call s:hi('LineNr', s:faint, s:none, 'NONE', '')
call s:hi('LineNrAbove', s:faint, s:none, 'NONE', '')
call s:hi('LineNrBelow', s:faint, s:none, 'NONE', '')
call s:hi('SignColumn', s:faint, s:none, 'NONE', '')
call s:hi('FoldColumn', s:faint, s:none, 'NONE', '')
call s:hi('Folded', s:subtext, s:surface0, 'NONE', '')
call s:hi('ColorColumn', s:none, s:surface0, 'NONE', '')
call s:hi('Visual', s:none, s:surface1, 'NONE', '')
call s:hi('VisualNOS', s:none, s:surface1, 'NONE', '')
call s:hi('Search', s:base, s:amber, 'NONE', '')
call s:hi('IncSearch', s:base, s:orange, 'NONE', '')
call s:hi('CurSearch', s:base, s:orange, s:bold, '')
call s:hi('Substitute', s:base, s:pink, 'NONE', '')
call s:hi('MatchParen', s:purple, s:surface1, s:bold, '')
call s:hi('NonText', s:surface2, s:none, 'NONE', '')
call s:hi('Whitespace', s:surface2, s:none, 'NONE', '')
call s:hi('SpecialKey', s:surface2, s:none, 'NONE', '')
call s:hi('EndOfBuffer', s:surface1, s:none, 'NONE', '')
call s:hi('Conceal', s:faint, s:none, 'NONE', '')
call s:hi('Directory', s:blue, s:none, s:bold, '')
call s:hi('Title', s:orange, s:none, s:bold, '')
call s:hi('ErrorMsg', s:pink, s:none, s:bold, '')
call s:hi('WarningMsg', s:amber, s:none, 'NONE', '')
call s:hi('ModeMsg', s:fg, s:none, s:bold, '')
call s:hi('MoreMsg', s:green, s:none, 'NONE', '')
call s:hi('Question', s:orange, s:none, 'NONE', '')
call s:hi('MsgArea', s:fg, s:none, 'NONE', '')
call s:hi('MsgSeparator', s:surface1, s:none, 'NONE', '')
call s:hi('StatusLine', s:fg, s:surface0, 'NONE', '')
call s:hi('StatusLineNC', s:faint, s:mantle, 'NONE', '')
call s:hi('WinBar', s:fg, s:none, s:bold, '')
call s:hi('WinBarNC', s:faint, s:none, 'NONE', '')
call s:hi('VertSplit', s:surface1, s:none, 'NONE', '')
call s:hi('WinSeparator', s:surface1, s:none, 'NONE', '')
call s:hi('TabLine', s:faint, s:mantle, 'NONE', '')
call s:hi('TabLineFill', s:none, s:crust, 'NONE', '')
call s:hi('TabLineSel', s:bright, s:base, s:bold, '')
call s:hi('Pmenu', s:fg, s:mantle, 'NONE', '')
call s:hi('PmenuSel', s:bright, s:surface1, s:bold, '')
call s:hi('PmenuSbar', s:none, s:surface0, 'NONE', '')
call s:hi('PmenuThumb', s:none, s:surface2, 'NONE', '')
call s:hi('PmenuKind', s:blue, s:mantle, 'NONE', '')
call s:hi('PmenuExtra', s:faint, s:mantle, 'NONE', '')
call s:hi('WildMenu', s:base, s:orange, 'NONE', '')
call s:hi('QuickFixLine', s:none, s:surface1, 'NONE', '')
call s:hi('SpellBad', s:none, s:none, 'undercurl', s:pink[0])
call s:hi('SpellCap', s:none, s:none, 'undercurl', s:amber[0])
call s:hi('SpellRare', s:none, s:none, 'undercurl', s:blue[0])
call s:hi('SpellLocal', s:none, s:none, 'undercurl', s:blue[0])
call s:hi('DiffAdd', s:green, s:none, 'NONE', '')
call s:hi('DiffChange', s:yellow, s:none, 'NONE', '')
call s:hi('DiffDelete', s:pink, s:none, 'NONE', '')
call s:hi('DiffText', s:base, s:yellow, 'NONE', '')
call s:hi('Added', s:green, s:none, 'NONE', '')
call s:hi('Changed', s:yellow, s:none, 'NONE', '')
call s:hi('Removed', s:pink, s:none, 'NONE', '')
call s:hi('Comment', s:subtext, s:none, s:italic, '')
call s:hi('Constant', s:light_blue, s:none, 'NONE', '')
call s:hi('String', s:green, s:none, 'NONE', '')
call s:hi('Character', s:green, s:none, 'NONE', '')
call s:hi('Number', s:light_blue, s:none, 'NONE', '')
call s:hi('Float', s:light_blue, s:none, 'NONE', '')
call s:hi('Boolean', s:light_blue, s:none, 'NONE', '')
call s:hi('Identifier', s:fg, s:none, 'NONE', '')
call s:hi('Function', s:purple, s:none, 'NONE', '')
call s:hi('Statement', s:orange, s:none, 'NONE', '')
call s:hi('Conditional', s:orange, s:none, 'NONE', '')
call s:hi('Repeat', s:orange, s:none, 'NONE', '')
call s:hi('Label', s:amber, s:none, 'NONE', '')
call s:hi('Operator', s:orange, s:none, 'NONE', '')
call s:hi('Keyword', s:orange, s:none, 'NONE', '')
call s:hi('Exception', s:orange, s:none, 'NONE', '')
call s:hi('PreProc', s:indigo, s:none, 'NONE', '')
call s:hi('Include', s:indigo, s:none, 'NONE', '')
call s:hi('Define', s:indigo, s:none, 'NONE', '')
call s:hi('Macro', s:indigo, s:none, 'NONE', '')
call s:hi('PreCondit', s:indigo, s:none, 'NONE', '')
call s:hi('Type', s:blue, s:none, 'NONE', '')
call s:hi('StorageClass', s:orange, s:none, 'NONE', '')
call s:hi('Structure', s:blue, s:none, 'NONE', '')
call s:hi('Typedef', s:blue, s:none, 'NONE', '')
call s:hi('Special', s:amber, s:none, 'NONE', '')
call s:hi('SpecialChar', s:amber, s:none, 'NONE', '')
call s:hi('Tag', s:orange, s:none, 'NONE', '')
call s:hi('Delimiter', s:subtext, s:none, 'NONE', '')
call s:hi('SpecialComment', s:subtext, s:none, s:italic, '')
call s:hi('Debug', s:amber, s:none, 'NONE', '')
call s:hi('Underlined', s:light_blue, s:none, 'underline', '')
call s:hi('Bold', s:none, s:none, s:bold, '')
call s:hi('Italic', s:none, s:none, s:italic, '')
call s:hi('Ignore', s:faint, s:none, 'NONE', '')
call s:hi('Error', s:pink, s:none, 'NONE', '')
call s:hi('Todo', s:orange, s:surface0, s:bold, '')
call s:hi('DiagnosticError', s:pink, s:none, 'NONE', '')
call s:hi('DiagnosticWarn', s:amber, s:none, 'NONE', '')
call s:hi('DiagnosticInfo', s:blue, s:none, 'NONE', '')
call s:hi('DiagnosticHint', s:subtext, s:none, 'NONE', '')
call s:hi('DiagnosticOk', s:green, s:none, 'NONE', '')
call s:hi('DiagnosticUnderlineError', s:none, s:none, 'undercurl', s:pink[0])
call s:hi('DiagnosticUnderlineWarn', s:none, s:none, 'undercurl', s:amber[0])
call s:hi('DiagnosticUnderlineInfo', s:none, s:none, 'undercurl', s:blue[0])
call s:hi('DiagnosticUnderlineHint', s:none, s:none, 'undercurl', s:subtext[0])
call s:hi('LspReferenceText', s:none, s:surface1, 'NONE', '')
call s:hi('LspReferenceRead', s:none, s:surface1, 'NONE', '')
call s:hi('LspReferenceWrite', s:none, s:surface1, 'NONE', '')
call s:hi('LspSignatureActiveParameter', s:fg, s:none, s:bold, '')
call s:hi('LspInlayHint', s:faint, s:none, s:italic, '')

" Treesitter captures (Neovim)
call s:hi('@comment', s:subtext, s:none, 'NONE', '')
call s:hi('@comment.documentation', s:subtext, s:none, 'NONE', '')
call s:hi('@string', s:green, s:none, 'NONE', '')
call s:hi('@string.documentation', s:subtext, s:none, 'NONE', '')
call s:hi('@string.escape', s:amber, s:none, 'NONE', '')
call s:hi('@string.regexp', s:pink, s:none, 'NONE', '')
call s:hi('@string.special', s:amber, s:none, 'NONE', '')
call s:hi('@character', s:green, s:none, 'NONE', '')
call s:hi('@number', s:light_blue, s:none, 'NONE', '')
call s:hi('@number.float', s:light_blue, s:none, 'NONE', '')
call s:hi('@boolean', s:light_blue, s:none, 'NONE', '')
call s:hi('@constant', s:light_blue, s:none, 'NONE', '')
call s:hi('@constant.builtin', s:amber, s:none, 'NONE', '')
call s:hi('@constant.macro', s:indigo, s:none, 'NONE', '')
call s:hi('@function', s:purple, s:none, 'NONE', '')
call s:hi('@function.builtin', s:amber, s:none, 'NONE', '')
call s:hi('@function.call', s:purple, s:none, 'NONE', '')
call s:hi('@function.method', s:purple, s:none, 'NONE', '')
call s:hi('@function.method.call', s:purple, s:none, 'NONE', '')
call s:hi('@function.macro', s:indigo, s:none, 'NONE', '')
call s:hi('@constructor', s:blue, s:none, 'NONE', '')
call s:hi('@keyword', s:orange, s:none, 'NONE', '')
call s:hi('@keyword.conditional', s:orange, s:none, 'NONE', '')
call s:hi('@keyword.repeat', s:orange, s:none, 'NONE', '')
call s:hi('@keyword.return', s:orange, s:none, 'NONE', '')
call s:hi('@keyword.exception', s:orange, s:none, 'NONE', '')
call s:hi('@keyword.import', s:indigo, s:none, 'NONE', '')
call s:hi('@keyword.operator', s:orange, s:none, 'NONE', '')
call s:hi('@keyword.function', s:orange, s:none, 'NONE', '')
call s:hi('@keyword.type', s:orange, s:none, 'NONE', '')
call s:hi('@keyword.modifier', s:orange, s:none, 'NONE', '')
call s:hi('@keyword.directive', s:indigo, s:none, 'NONE', '')
call s:hi('@type', s:blue, s:none, 'NONE', '')
call s:hi('@type.builtin', s:amber, s:none, 'NONE', '')
call s:hi('@type.definition', s:blue, s:none, 'NONE', '')
call s:hi('@attribute', s:amber, s:none, 'NONE', '')
call s:hi('@property', s:light_green, s:none, 'NONE', '')
call s:hi('@variable', s:fg, s:none, 'NONE', '')
call s:hi('@variable.builtin', s:amber, s:none, 'NONE', '')
call s:hi('@variable.member', s:light_green, s:none, 'NONE', '')
call s:hi('@variable.parameter', s:fg, s:none, 'NONE', '')
call s:hi('@module', s:blue, s:none, 'NONE', '')
call s:hi('@label', s:amber, s:none, 'NONE', '')
call s:hi('@operator', s:orange, s:none, 'NONE', '')
call s:hi('@punctuation.bracket', s:subtext, s:none, 'NONE', '')
call s:hi('@punctuation.delimiter', s:subtext, s:none, 'NONE', '')
call s:hi('@punctuation.special', s:amber, s:none, 'NONE', '')
call s:hi('@tag', s:orange, s:none, 'NONE', '')
call s:hi('@tag.attribute', s:amber, s:none, 'NONE', '')
call s:hi('@tag.delimiter', s:subtext, s:none, 'NONE', '')
call s:hi('@markup.raw', s:green, s:none, 'NONE', '')
call s:hi('@markup.link', s:light_blue, s:none, 'NONE', '')
call s:hi('@markup.list', s:orange, s:none, 'NONE', '')
call s:hi('@diff.plus', s:green, s:none, 'NONE', '')
call s:hi('@diff.minus', s:pink, s:none, 'NONE', '')
call s:hi('@diff.delta', s:yellow, s:none, 'NONE', '')
call s:hi('@markup.heading', s:orange, s:none, s:bold, '')
call s:hi('@markup.strong', s:none, s:none, s:bold, '')
call s:hi('@markup.italic', s:none, s:none, s:italic, '')
call s:hi('@markup.strikethrough', s:faint, s:none, 'strikethrough', '')
call s:hi('@comment.error', s:pink, s:none, 'NONE', '')
call s:hi('@comment.warning', s:amber, s:none, 'NONE', '')
call s:hi('@comment.todo', s:orange, s:surface0, s:bold, '')
call s:hi('@comment.note', s:blue, s:none, 'NONE', '')

" Terminal palette
let g:terminal_ansi_colors = [
      \ '#362f2a', '#b77f94', '#89a17e', '#b4a075',
      \ '#8198b5', '#ad8eaf', '#789fa6', '#b9b1a9',
      \ '#786d63', '#b78396', '#8da281', '#b4a179',
      \ '#859ab4', '#ae91af', '#7da0a6', '#cbc3ba'
      \ ]
if has('nvim')
  let g:terminal_color_0 = '#362f2a'
  let g:terminal_color_1 = '#b77f94'
  let g:terminal_color_2 = '#89a17e'
  let g:terminal_color_3 = '#b4a075'
  let g:terminal_color_4 = '#8198b5'
  let g:terminal_color_5 = '#ad8eaf'
  let g:terminal_color_6 = '#789fa6'
  let g:terminal_color_7 = '#b9b1a9'
  let g:terminal_color_8 = '#786d63'
  let g:terminal_color_9 = '#b78396'
  let g:terminal_color_10 = '#8da281'
  let g:terminal_color_11 = '#b4a179'
  let g:terminal_color_12 = '#859ab4'
  let g:terminal_color_13 = '#ae91af'
  let g:terminal_color_14 = '#7da0a6'
  let g:terminal_color_15 = '#cbc3ba'
endif

delfunction s:hi
