#!/usr/bin/env bash
# Generated by tools/generate.py from palette.toml. Do not edit.
#
# TPM entry point. With
#   set -g @plugin 'ymotongpoo/grafana-color-scheme'
# TPM runs this file, which sources the theme selected by @grafana_variant.
#
#   set -g @grafana_variant 'dark'    # or 'light'
#   set -g @grafana_status  'off'     # 'on' to also take the status layout

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

variant="$(tmux show-option -gqv '@grafana_variant')"
[ -n "$variant" ] || variant="dark"
case "$variant" in
  dark|light) ;;
  *)
    tmux display-message "grafana-color-scheme: unknown @grafana_variant '$variant', using dark"
    variant="dark"
    ;;
esac

tmux source-file "$DIR/src/grafana-$variant.conf"

status="$(tmux show-option -gqv '@grafana_status')"
if [ "$status" = "on" ]; then
  tmux source-file "$DIR/src/grafana-$variant-status.conf"
fi
