"""Chroma styles and stylesheets.

Two artifacts per variant, because Chroma has two consumer populations:

  styles/*.xml  Go programs can load these at runtime with
                chroma.NewXMLStyle, and it is the file shape the upstream
                `styles/` directory expects if this is ever contributed.

  css/*.css     Hugo CANNOT load a custom Chroma XML -- markup.highlight.style
                only accepts names compiled into Hugo. Hugo users need
                pre-generated classes plus `noClasses = false`.

The XML filename stem must equal the lowercased style name; upstream Chroma
has a test asserting that invariant.
"""

from __future__ import annotations

from ..palette import Palette, Variant
from . import chroma_tokens as T

HEADER = "Generated by tools/generate.py from palette.toml. Do not edit."


def _token_styles(v: Variant) -> dict[str, tuple[str, str]]:
    """Chroma TokenType -> (hex or "", extra attributes).

    Returned in TOKENS order by the callers so both artifacts agree.
    """
    r = v.rc
    role = v.role
    diff = v.diff

    def styled(role_name: str) -> tuple[str, str]:
        ro = role(role_name)
        bits = []
        if ro.bold:
            bits.append("bold")
        if ro.italic:
            bits.append("italic")
        if ro.underline:
            bits.append("underline")
        return ro.color, " ".join(bits)

    m: dict[str, tuple[str, str]] = {
        "Other": (v.text["fg"], ""),
        "Error": (v.diagnostic["error"].color, ""),
        "Keyword": styled("keyword"),
        "KeywordConstant": (r("constant"), ""),
        "KeywordDeclaration": styled("keyword"),
        "KeywordNamespace": styled("keyword"),
        "KeywordPseudo": styled("keyword"),
        "KeywordReserved": styled("keyword"),
        "KeywordType": (r("type"), ""),
        "NameAttribute": (r("attribute"), ""),
        "NameClass": (r("class"), ""),
        "NameConstant": (r("constant"), ""),
        "NameDecorator": (r("decorator"), ""),
        "NameEntity": (r("function"), ""),
        "NameException": (r("class"), ""),
        "NameLabel": (r("label"), ""),
        "NameNamespace": (r("namespace"), ""),
        "NameOther": (v.text["fg"], ""),
        "NameTag": (r("tag"), ""),
        "NameBuiltin": (r("builtin"), ""),
        "NameBuiltinPseudo": (r("builtin"), ""),
        "NameVariable": (r("variable"), ""),
        "NameVariableClass": (r("variable"), ""),
        "NameVariableGlobal": (r("variable"), ""),
        "NameVariableInstance": (r("variable"), ""),
        "NameVariableMagic": (r("variable"), ""),
        "NameFunction": (r("function"), ""),
        "NameFunctionMagic": (r("function"), ""),
        "LiteralDate": (r("number"), ""),
        "LiteralString": (r("string"), ""),
        "LiteralStringAffix": (r("string"), ""),
        "LiteralStringBacktick": (r("string"), ""),
        "LiteralStringChar": (r("string"), ""),
        "LiteralStringDelimiter": (r("string"), ""),
        "LiteralStringDoc": styled("string-doc"),
        "LiteralStringDouble": (r("string"), ""),
        "LiteralStringEscape": (r("string-escape"), ""),
        "LiteralStringHeredoc": (r("string"), ""),
        "LiteralStringInterpol": (r("string-escape"), ""),
        "LiteralStringOther": (r("string"), ""),
        "LiteralStringRegex": (r("regex"), ""),
        "LiteralStringSingle": (r("string"), ""),
        "LiteralStringSymbol": (r("string"), ""),
        "LiteralNumber": (r("number"), ""),
        "LiteralNumberBin": (r("number"), ""),
        "LiteralNumberFloat": (r("number"), ""),
        "LiteralNumberHex": (r("number"), ""),
        "LiteralNumberInteger": (r("number"), ""),
        "LiteralNumberIntegerLong": (r("number"), ""),
        "LiteralNumberOct": (r("number"), ""),
        "Operator": (r("operator"), ""),
        "OperatorWord": styled("keyword"),
        "OperatorReserved": styled("keyword"),
        "Punctuation": (r("punctuation"), ""),
        "Comment": styled("comment"),
        "CommentHashbang": styled("comment"),
        "CommentMultiline": styled("comment"),
        "CommentSingle": styled("comment"),
        "CommentSpecial": (v.rc("comment"), "italic bold"),
        "CommentPreproc": (r("preprocessor"), ""),
        "CommentPreprocFile": (r("string"), ""),
        "GenericDeleted": (diff["removed"].color, ""),
        "GenericEmph": ("", "italic"),
        "GenericError": (v.diagnostic["error"].color, ""),
        "GenericHeading": styled("heading"),
        "GenericInserted": (diff["added"].color, ""),
        "GenericOutput": (v.text["subtext"], ""),
        "GenericPrompt": (r("keyword"), "bold"),
        "GenericStrong": ("", "bold"),
        "GenericSubheading": (r("builtin"), "bold"),
        "GenericTraceback": (v.diagnostic["error"].color, ""),
        "GenericUnderline": ("", "underline"),
        "TextWhitespace": (v.surfaces["surface1"], ""),
    }
    return m


def _xml(p: Palette, v: Variant, counterpart: str) -> str:
    styles = _token_styles(v)
    lines = [
        f"<!-- {HEADER} -->",
        f'<style name="{v.id}" counterpart="{counterpart}">',
        f'  <entry type="Background" style="{v.text["fg"]} bg:{v.surfaces["base"]}"/>',
    ]
    for token, _cls in T.TOKENS:
        if token in T.STRUCTURAL.values() or token in ("Line", "CodeLine", "LineLink", "LineTableTD", "LineTable"):
            continue
        if token == "LineHighlight":
            lines.append(f'  <entry type="LineHighlight" style="bg:{v.surfaces["surface0"]}"/>')
            continue
        if token in ("LineNumbers", "LineNumbersTable"):
            lines.append(f'  <entry type="{token}" style="{v.text["faint"]}"/>')
            continue
        hexv, attrs = styles[token]
        spec = " ".join(x for x in (attrs, hexv) if x)
        lines.append(f'  <entry type="{token}" style="{spec}"/>')
    lines.append("</style>")
    return "\n".join(lines) + "\n"


def _css(v: Variant, *, scope: str = ".chroma", prefix: str = "") -> list[str]:
    """Chroma-compatible class rules. `prefix` scopes them for the combined
    stylesheet so both variants can live in one file."""
    styles = _token_styles(v)
    out: list[str] = []
    sel = f"{prefix}{scope}"
    out.append(
        f"{sel} {{ color: {v.text['fg']}; background-color: {v.surfaces['base']}; "
        "tab-size: 4; -webkit-text-size-adjust: none; }"
    )
    out.append(f"{prefix}.bg {{ color: {v.text['fg']}; background-color: {v.surfaces['base']}; }}")
    for cls, decl in T.STRUCTURAL.items():
        out.append(f"{sel} .{cls} {{ {decl} }}")
    out.append(f"{sel} .hl {{ background-color: {v.surfaces['surface0']} }}")
    for cls in ("lnt", "ln"):
        out.append(
            f"{sel} .{cls} {{ white-space: pre; user-select: none; margin-right: 0.4em; "
            f"padding: 0 0.4em; color: {v.text['faint']} }}"
        )
    for token, cls in T.TOKENS:
        if cls in T.STRUCTURAL or cls in ("hl", "lnt", "ln", "cl"):
            continue
        hexv, attrs = styles[token]
        decls = []
        if hexv:
            decls.append(f"color: {hexv}")
        if "bold" in attrs:
            decls.append("font-weight: bold")
        if "italic" in attrs:
            decls.append("font-style: italic")
        if "underline" in attrs:
            decls.append("text-decoration: underline")
        if not decls:
            continue
        out.append(f"{sel} .{cls} {{ {'; '.join(decls)} }}")
    return out


def emit(p: Palette) -> dict[str, str]:
    files: dict[str, str] = {}
    ids = {name: v.id for name, v in p.each()}

    for name, v in p.each():
        other = "light" if name == "dark" else "dark"
        files[f"styles/{v.id}.xml"] = _xml(p, v, ids[other])
        body = "\n".join(
            [
                f"/* {HEADER} */",
                f"/* {v.label} for Chroma. Requires markup.highlight.noClasses = false in Hugo. */",
                "",
                *_css(v),
            ]
        )
        files[f"css/{v.id}.css"] = body + "\n"

    dark = p.variant("dark")
    light = p.variant("light")
    auto = [
        f"/* {HEADER} */",
        "/* Both variants in one stylesheet. Follows the reader's system setting,",
        '   and an explicit data-theme="light" | "dark" on the root element wins. */',
        "",
        *_css(light),
        "",
        "@media (prefers-color-scheme: dark) {",
        *[f"  {line}" for line in _css(dark, prefix=":root:not([data-theme='light']) ")],
        "}",
        "",
        *_css(dark, prefix=":root[data-theme='dark'] "),
        "",
        *_css(light, prefix=":root[data-theme='light'] "),
    ]
    files["css/grafana-auto.css"] = "\n".join(auto) + "\n"
    return files
