"""Emacs custom themes.

The `-theme.el` suffix is mandatory: Emacs derives the theme symbol from the
basename. The first form in the file must be `deftheme` and the last
`provide-theme`.

One display spec, `((class color) (min-colors 89))`, so the theme works in
GUI and in any terminal Emacs believes has enough colors. A 256-color
terminal gets Emacs's own approximation of these hexes, which is the tradeoff
every modern theme makes; a per-face dual spec would roughly triple the file
for a case that is increasingly rare.
"""

from __future__ import annotations

from ..palette import Palette, Variant

HEADER = "Generated by tools/generate.py from palette.toml. Do not edit."


def _let_bindings(v: Variant) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for key in ("crust", "mantle", "base", "surface0", "surface1", "surface2"):
        out.append((key.replace("_", "-"), v.surfaces[key]))
    for key in ("bright", "fg", "subtext", "faint"):
        out.append((key, v.text[key]))
    for key, val in v.accents.items():
        out.append((key, val))
    return out


def _faces(v: Variant) -> list[tuple[str, str]]:
    """(face name, attribute string). Colors are emitted as ,symbol refs."""
    r = lambda name: v.role(name).token  # noqa: E731  -- symbol name, not hex
    err = v.diagnostic["error"].token
    warn = v.diagnostic["warning"].token
    info = v.diagnostic["info"].token
    ok = v.diagnostic["ok"].token
    added = v.diff["added"].token
    removed = v.diff["removed"].token
    changed = v.diff["changed"].token

    def italic(name: str) -> str:
        return " :slant italic" if v.role(name).italic else ""

    return [
        # Basic faces
        ("default", f":foreground ,fg :background ,base"),
        ("cursor", f":background ,{r('keyword')}"),
        ("region", f":background ,surface1 :distant-foreground ,bright :extend t"),
        ("highlight", f":background ,surface1"),
        ("hl-line", f":background ,surface0 :extend t"),
        ("fringe", f":foreground ,faint :background ,base"),
        ("vertical-border", f":foreground ,surface1"),
        ("window-divider", f":foreground ,surface1"),
        ("window-divider-first-pixel", f":foreground ,surface1"),
        ("window-divider-last-pixel", f":foreground ,surface1"),
        ("minibuffer-prompt", f":foreground ,{r('keyword')} :weight bold"),
        ("shadow", f":foreground ,faint"),
        ("link", f":foreground ,{r('link')} :underline t"),
        ("link-visited", f":foreground ,{r('function')} :underline t"),
        ("error", f":foreground ,{err} :weight bold"),
        ("warning", f":foreground ,{warn} :weight bold"),
        ("success", f":foreground ,{ok} :weight bold"),
        ("escape-glyph", f":foreground ,{r('string-escape')}"),
        ("homoglyph", f":foreground ,{warn}"),
        ("nobreak-space", f":foreground ,faint :underline t"),
        ("nobreak-hyphen", f":foreground ,faint"),
        ("trailing-whitespace", f":background ,{err}"),
        ("whitespace-trailing", f":background ,{err} :foreground ,base"),
        ("whitespace-tab", f":foreground ,surface2 :background ,base"),
        ("whitespace-space", f":foreground ,surface2 :background ,base"),
        ("whitespace-line", f":background ,surface0"),
        ("secondary-selection", f":background ,surface0 :extend t"),
        ("match", f":background ,{r('function')} :foreground ,base"),
        ("isearch", f":background ,{r('keyword')} :foreground ,base :weight bold"),
        ("isearch-fail", f":background ,{err} :foreground ,base"),
        ("lazy-highlight", f":background ,surface1 :foreground ,{r('keyword')}"),
        ("show-paren-match", f":foreground ,{r('function')} :background ,surface1 :weight bold"),
        ("show-paren-mismatch", f":foreground ,bright :background ,{err} :weight bold"),
        ("tooltip", f":foreground ,fg :background ,mantle"),
        ("help-key-binding", f":foreground ,{r('builtin')} :background ,surface0"),
        # Line numbers, mode line, header, tabs
        ("line-number", f":foreground ,faint :background ,base"),
        ("line-number-current-line", f":foreground ,fg :background ,surface0 :weight bold"),
        ("mode-line", f":foreground ,fg :background ,surface0 :box nil"),
        ("mode-line-inactive", f":foreground ,faint :background ,mantle :box nil"),
        ("mode-line-buffer-id", f":foreground ,{r('keyword')} :weight bold"),
        ("mode-line-highlight", f":foreground ,{r('function')}"),
        ("mode-line-emphasis", f":foreground ,{r('keyword')} :weight bold"),
        ("header-line", f":foreground ,fg :background ,mantle"),
        ("tab-bar", f":foreground ,faint :background ,mantle"),
        ("tab-bar-tab", f":foreground ,bright :background ,base :weight bold"),
        ("tab-bar-tab-inactive", f":foreground ,faint :background ,mantle"),
        ("tab-line", f":foreground ,faint :background ,mantle"),
        # font-lock
        ("font-lock-builtin-face", f":foreground ,{r('builtin')}"),
        ("font-lock-comment-face", f":foreground ,{r('comment')}{italic('comment')}"),
        ("font-lock-comment-delimiter-face", f":foreground ,{r('comment')}{italic('comment')}"),
        ("font-lock-doc-face", f":foreground ,{r('comment-doc')}{italic('comment-doc')}"),
        ("font-lock-doc-markup-face", f":foreground ,{r('property')}"),
        ("font-lock-constant-face", f":foreground ,{r('constant')}"),
        ("font-lock-function-name-face", f":foreground ,{r('function')}"),
        ("font-lock-function-call-face", f":foreground ,{r('function')}"),
        ("font-lock-keyword-face", f":foreground ,{r('keyword')}"),
        ("font-lock-negation-char-face", f":foreground ,{r('operator')}"),
        ("font-lock-number-face", f":foreground ,{r('number')}"),
        ("font-lock-operator-face", f":foreground ,{r('operator')}"),
        ("font-lock-preprocessor-face", f":foreground ,{r('preprocessor')}"),
        ("font-lock-property-name-face", f":foreground ,{r('property')}"),
        ("font-lock-property-use-face", f":foreground ,{r('property')}"),
        ("font-lock-punctuation-face", f":foreground ,{r('punctuation')}"),
        ("font-lock-bracket-face", f":foreground ,{r('punctuation')}"),
        ("font-lock-delimiter-face", f":foreground ,{r('punctuation')}"),
        ("font-lock-escape-face", f":foreground ,{r('string-escape')}"),
        ("font-lock-regexp-face", f":foreground ,{r('regex')}"),
        ("font-lock-regexp-grouping-backslash", f":foreground ,{r('string-escape')}"),
        ("font-lock-regexp-grouping-construct", f":foreground ,{r('regex')}"),
        ("font-lock-string-face", f":foreground ,{r('string')}"),
        ("font-lock-type-face", f":foreground ,{r('type')}"),
        ("font-lock-variable-name-face", f":foreground ,{r('variable')}"),
        ("font-lock-variable-use-face", f":foreground ,{r('variable')}"),
        ("font-lock-warning-face", f":foreground ,{warn} :weight bold"),
        ("font-lock-misc-punctuation-face", f":foreground ,{r('punctuation')}"),
        # diff and version control
        ("diff-added", f":foreground ,{added} :extend t"),
        ("diff-removed", f":foreground ,{removed} :extend t"),
        ("diff-changed", f":foreground ,{changed} :extend t"),
        ("diff-indicator-added", f":foreground ,{added}"),
        ("diff-indicator-removed", f":foreground ,{removed}"),
        ("diff-header", f":foreground ,fg :background ,mantle :extend t"),
        ("diff-file-header", f":foreground ,bright :weight bold :extend t"),
        ("diff-hunk-header", f":foreground ,{r('heading')} :background ,mantle :extend t"),
        ("diff-refine-added", f":foreground ,base :background ,{added}"),
        ("diff-refine-removed", f":foreground ,base :background ,{removed}"),
        # completion, dired, flymake, compilation
        ("completions-common-part", f":foreground ,{r('keyword')} :weight bold"),
        ("completions-first-difference", f":foreground ,{r('function')}"),
        ("completions-annotations", f":foreground ,{r('comment')}{italic('comment')}"),
        ("dired-directory", f":foreground ,{r('type')} :weight bold"),
        ("dired-symlink", f":foreground ,{r('function')}"),
        ("dired-header", f":foreground ,{r('heading')} :weight bold"),
        ("dired-ignored", f":foreground ,faint"),
        ("flymake-error", f":underline (:style wave :color ,{err})"),
        ("flymake-warning", f":underline (:style wave :color ,{warn})"),
        ("flymake-note", f":underline (:style wave :color ,{info})"),
        ("compilation-error", f":foreground ,{err} :weight bold"),
        ("compilation-warning", f":foreground ,{warn}"),
        ("compilation-info", f":foreground ,{info}"),
        ("compilation-mode-line-fail", f":foreground ,{err}"),
        ("compilation-mode-line-run", f":foreground ,{warn}"),
        ("compilation-mode-line-exit", f":foreground ,{ok}"),
        # org-mode
        ("org-level-1", f":foreground ,{r('heading')} :weight bold"),
        ("org-level-2", f":foreground ,{r('function')} :weight bold"),
        ("org-level-3", f":foreground ,{r('type')} :weight bold"),
        ("org-level-4", f":foreground ,{r('string')} :weight bold"),
        ("org-level-5", f":foreground ,{r('number')}"),
        ("org-level-6", f":foreground ,{r('preprocessor')}"),
        ("org-document-title", f":foreground ,bright :weight bold"),
        ("org-block", f":background ,mantle :extend t"),
        ("org-block-begin-line", f":foreground ,faint :background ,mantle :extend t"),
        ("org-block-end-line", f":foreground ,faint :background ,mantle :extend t"),
        ("org-code", f":foreground ,{r('string')}"),
        ("org-verbatim", f":foreground ,{r('string')}"),
        ("org-table", f":foreground ,{r('type')}"),
        ("org-link", f":foreground ,{r('link')} :underline t"),
        ("org-todo", f":foreground ,{err} :weight bold"),
        ("org-done", f":foreground ,{ok} :weight bold"),
        ("org-headline-done", f":foreground ,faint"),
        ("org-date", f":foreground ,{r('number')} :underline t"),
        ("org-special-keyword", f":foreground ,{r('keyword')}"),
        ("org-checkbox", f":foreground ,{r('keyword')} :weight bold"),
        ("org-agenda-date", f":foreground ,{r('type')}"),
        ("org-agenda-done", f":foreground ,{ok}"),
        ("org-scheduled", f":foreground ,{r('string')}"),
        ("org-warning", f":foreground ,{warn} :weight bold"),
        # markdown
        ("markdown-header-face", f":foreground ,{r('heading')} :weight bold"),
        ("markdown-code-face", f":foreground ,{r('string')} :background ,mantle"),
        ("markdown-inline-code-face", f":foreground ,{r('string')}"),
        ("markdown-link-face", f":foreground ,{r('link')}"),
        ("markdown-url-face", f":foreground ,{r('link')} :underline t"),
        ("markdown-blockquote-face", f":foreground ,{r('comment')}{italic('comment')}"),
        ("markdown-list-face", f":foreground ,{r('keyword')}"),
        # terminal / ansi
        ("term-color-black", f":foreground ,surface1 :background ,surface1"),
        ("term-color-red", f":foreground ,{r('regex')} :background ,{r('regex')}"),
        ("term-color-green", f":foreground ,{r('string')} :background ,{r('string')}"),
        ("term-color-yellow", f":foreground ,{r('builtin')} :background ,{r('builtin')}"),
        ("term-color-blue", f":foreground ,{r('type')} :background ,{r('type')}"),
        ("term-color-magenta", f":foreground ,{r('function')} :background ,{r('function')}"),
        ("term-color-cyan", f":foreground ,{r('number')} :background ,{r('number')}"),
        ("term-color-white", f":foreground ,fg :background ,fg"),
    ]


def _theme(p: Palette, v: Variant) -> str:
    bindings = _let_bindings(v)
    width = max(len(name) for name, _ in bindings)
    let_lines = []
    let_lines.append("(let ((class '((class color) (min-colors 89)))")
    for i, (name, hexv) in enumerate(bindings):
        pad = name.ljust(width)
        prefix = "      " if i or True else ""
        let_lines.append(f'{prefix}({pad} "{hexv}")')
    let_lines[-1] = let_lines[-1] + ")"

    face_lines = []
    for face, attrs in _faces(v):
        face_lines.append(f"   `({face} ((,class ({attrs}))))")

    ansi = v.ansi("dim")
    vector = " ".join(f'"{ansi[i]}"' for i in (0, 1, 2, 3, 4, 5, 6, 7))

    return f"""\
;;; {v.id}-theme.el --- {v.label} -*- lexical-binding: t; -*-

;; Copyright (c) 2026 {p.scheme['author']}

;; Author: {p.scheme['author']}
;; URL: {p.scheme['homepage']}
;; Version: 1.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: faces, theme
;; SPDX-License-Identifier: {p.scheme['license']}

;;; Commentary:

;; {v.label}, derived from the Grafana Labs brand palette.  Every syntax
;; token clears WCAG AA (4.5:1) against the background, and comments are
;; kept clear of the threshold so they read as prose rather than as noise.
;;
;; {HEADER}
;; This is not an official Grafana Labs project.

;;; Code:

(deftheme {v.id}
  "{v.label}, a dim color scheme from the Grafana Labs brand palette.")

{chr(10).join(let_lines)}

  (custom-theme-set-faces
   '{v.id}

{chr(10).join(face_lines)})

  (custom-theme-set-variables
   '{v.id}
   `(ansi-color-names-vector [{vector}])))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme '{v.id})

;;; {v.id}-theme.el ends here
"""


def emit(p: Palette) -> dict[str, str]:
    return {f"{v.id}-theme.el": _theme(p, v) for _n, v in p.each()}
