"""Herdr theme fragments.

Herdr (https://herdr.dev) compiles its themes into the binary; there is no
~/.config/herdr/themes/ loader. The only way to carry an outside palette in
is per-token overrides under [theme.custom], so the deliverable here is a
pasteable config.toml fragment rather than a theme file.

Herdr's token vocabulary is Catppuccin-flavored (mauve, peach, teal,
subtext0, surface0/1, overlay0/1), so the mapping below is lossy by
construction -- "peach" is our orange, "mauve" our purple. The target README
carries the table.

There is also a zero-config route worth preferring: theme.name = "terminal"
makes Herdr follow the host terminal's ANSI palette, so the WezTerm or iTerm2
file in this repo already covers it.
"""

from __future__ import annotations

from ..palette import Palette, Variant

HEADER = "Generated by tools/generate.py from palette.toml. Do not edit."

# Herdr token -> our token reference. The full CustomThemeColors set is 19
# fields; all of them are emitted so nothing falls back to Catppuccin.
MAPPING: tuple[tuple[str, str], ...] = (
    ("accent", "accents.orange"),
    ("panel_bg", "surfaces.base"),
    ("sidebar_bg", "surfaces.mantle"),
    ("active_row_bg", "surfaces.surface0"),
    ("selection_bg", "surfaces.surface1"),
    ("surface0", "surfaces.surface0"),
    ("surface1", "surfaces.surface1"),
    ("surface_dim", "surfaces.crust"),
    ("overlay0", "surfaces.surface2"),
    ("overlay1", "text.faint"),
    ("text", "text.fg"),
    ("subtext0", "text.subtext"),
    ("mauve", "accents.purple"),
    ("green", "accents.green"),
    ("yellow", "accents.amber"),
    ("red", "accents.pink"),
    ("blue", "accents.blue"),
    ("teal", "accents.light-green"),
    ("peach", "accents.orange"),
)

# Where a Herdr name and ours genuinely disagree, say so inline.
NOTES = {
    "yellow": "our amber; the brand yellow is reserved for diff-changed",
    "red": "the Grafana brand has no red, so pink carries it",
    "teal": "our light-green",
    "peach": "our orange, same as accent",
    "mauve": "our purple",
}


def _fragment(p: Palette, v: Variant) -> str:
    width = max(len(name) for name, _ in MAPPING)
    lines = [
        f"# {HEADER}",
        "#",
        f"# {v.label} for Herdr. Herdr has no external theme files, so paste",
        "# this into ~/.config/herdr/config.toml and reload with:",
        "#   herdr server reload-config",
        "#",
        "# Simpler alternative: set theme.name = \"terminal\" and install the",
        "# WezTerm or iTerm2 scheme from this repo, and Herdr follows the host",
        "# terminal's ANSI palette with no per-token overrides at all.",
        "",
        "[theme]",
        'name = "terminal"',
        "auto_switch = false",
        "",
        "[theme.custom]",
    ]
    for name, ref in MAPPING:
        note = NOTES.get(name)
        comment = f"   # {note}" if note else ""
        lines.append(f'{name.ljust(width)} = "{v.color(ref)}"{comment}')

    other = "light" if v.name == "dark" else "dark"
    lines += [
        "",
        "# With auto_switch = true, Herdr layers [theme.custom.light] and",
        f"# [theme.custom.dark] on top of [theme.custom]. See {p.variant(other).id}",
        "# in this directory for the other half.",
    ]
    return "\n".join(lines) + "\n"


def _combined(p: Palette) -> str:
    dark = p.variant("dark")
    light = p.variant("light")
    width = max(len(name) for name, _ in MAPPING)
    lines = [
        f"# {HEADER}",
        "#",
        "# Both variants, following the host terminal's light/dark appearance.",
        "# Paste into ~/.config/herdr/config.toml.",
        "#",
        "# Precedence is: built-in theme -> [theme.custom] -> the matching",
        "# [theme.custom.light] or [theme.custom.dark] sub-table.",
        "",
        "[theme]",
        'name = "terminal"',
        "auto_switch = true",
        "",
        "[theme.custom]",
    ]
    for name, ref in MAPPING:
        note = NOTES.get(name)
        comment = f"   # {note}" if note else ""
        lines.append(f'{name.ljust(width)} = "{dark.color(ref)}"{comment}')
    for appearance, v in (("dark", dark), ("light", light)):
        lines += ["", f"[theme.custom.{appearance}]"]
        for name, ref in MAPPING:
            lines.append(f'{name.ljust(width)} = "{v.color(ref)}"')
    return "\n".join(lines) + "\n"


def emit(p: Palette) -> dict[str, str]:
    files = {f"{v.id}.config.toml": _fragment(p, v) for _n, v in p.each()}
    files["grafana-auto.config.toml"] = _combined(p)
    return files
