"""tmux themes.

Only *-style options are emitted; the legacy *-fg / *-bg / *-attr options
were removed in tmux 2.9.

Colors and status-line CONTENT are split into separate files because most
people already have a status line they like and only want the palette. The
palette is also published as @grafana_* user options so a user's own format
strings can reference it as #{@grafana_blue}.

terminal-features / terminal-overrides are deliberately NOT set here. They
are server options, so getting them wrong breaks colors everywhere; the
README tells the user what to add instead.
"""

from __future__ import annotations

from ..palette import Palette, Variant

HEADER = "Generated by tools/generate.py from palette.toml. Do not edit."

# Palette entries published as user options, in a stable order.
_EXPORTED = (
    ("bg", "surfaces.base"),
    ("bg_alt", "surfaces.mantle"),
    ("surface", "surfaces.surface0"),
    ("border", "surfaces.surface1"),
    ("fg", "text.fg"),
    ("subtext", "text.subtext"),
    ("faint", "text.faint"),
    ("bright", "text.bright"),
    ("orange", "accents.orange"),
    ("amber", "accents.amber"),
    ("yellow", "accents.yellow"),
    ("green", "accents.green"),
    ("light_green", "accents.light-green"),
    ("light_blue", "accents.light-blue"),
    ("blue", "accents.blue"),
    ("indigo", "accents.indigo"),
    ("purple", "accents.purple"),
    ("pink", "accents.pink"),
)


def _theme(v: Variant) -> str:
    s, txt = v.surfaces, v.text
    accent = v.rc("keyword")
    lines = [
        f"# {HEADER}",
        "#",
        f"# {v.label} for tmux. Colors only -- no status-line content.",
        "# Source from ~/.tmux.conf:",
        f"#   source-file ~/.config/tmux/grafana/{v.id}.conf",
        "#",
        "# Truecolor needs the terminal to advertise it. tmux 3.2+:",
        "#   set -as terminal-features ',*:RGB'",
        "# See the target README; this file does not set server options.",
        "",
        "#+--- Palette, published as user options ---+",
    ]
    for name, ref in _EXPORTED:
        lines.append(f'set -gq @grafana_{name} "{v.color(ref)}"')

    lines += [
        "",
        "#+--- Status line ---+",
        "set -g status on",
        "set -g status-interval 5",
        "set -g status-justify left",
        f'set -g status-style "bg={s["mantle"]},fg={txt["fg"]}"',
        'set -g status-left-style "default"',
        'set -g status-right-style "default"',
        "",
        "#+--- Windows ---+",
        f'set -g window-status-style "bg={s["mantle"]},fg={txt["faint"]}"',
        f'set -g window-status-current-style "bg={s["base"]},fg={accent},bold"',
        f'set -g window-status-last-style "fg={v.rc("function")}"',
        f'set -g window-status-activity-style "fg={v.diagnostic["warning"].color},none"',
        f'set -g window-status-bell-style "fg={v.diagnostic["error"].color},none"',
        "",
        "#+--- Panes ---+",
        f'set -g pane-border-style "bg=default,fg={s["surface1"]}"',
        f'set -g pane-active-border-style "bg=default,fg={accent}"',
        f'set -g pane-status-style "bg={s["mantle"]},fg={txt["faint"]}"',
        f'set -g pane-status-current-style "bg={s["mantle"]},fg={accent}"',
        f'set -g display-panes-colour "{s["surface2"]}"',
        f'set -g display-panes-active-colour "{accent}"',
        "",
        "#+--- Messages and the command prompt ---+",
        f'set -g message-style "bg={s["surface0"]},fg={v.rc("function")}"',
        f'set -g message-command-style "bg={s["surface0"]},fg={v.rc("function")}"',
        "",
        "#+--- Copy and choose modes ---+",
        f'set -g mode-style "bg={v.terminal["selection_bg"]},fg={v.terminal["selection_fg"]}"',
        f'set -g copy-mode-match-style "bg={v.diagnostic["warning"].color},fg={s["base"]}"',
        f'set -g copy-mode-current-match-style "bg={v.rc("keyword")},fg={s["base"]}"',
        f'set -g copy-mode-selection-style "bg={v.terminal["selection_bg"]},fg={v.terminal["selection_fg"]}"',
        f'set -g copy-mode-mark-style "bg={v.rc("function")},fg={s["base"]}"',
        "",
        "#+--- Clock ---+",
        f'setw -g clock-mode-colour "{accent}"',
        "setw -g clock-mode-style 24",
        "",
        "#+--- Popups and menus (tmux 3.2+) ---+",
        "if-shell -b '[ \"$(tmux -V | cut -d\" \" -f2 | tr -d \"a-z\")\" \\!= \"\" ] && "
        "[ \"$(printf \"%s\\\\n3.2\\\\n\" \"$(tmux -V | cut -d\" \" -f2 | tr -d \"a-z\")\" | sort -V | head -1)\" = \"3.2\" ]' \\",
        f'  \'set -g popup-style "bg={s["mantle"]},fg={txt["fg"]}" ; \\',
        f'   set -g popup-border-style "fg={accent}" ; \\',
        f'   set -g menu-style "bg={s["mantle"]},fg={txt["fg"]}" ; \\',
        f'   set -g menu-selected-style "bg={v.rc("function")},fg={s["base"]}" ; \\',
        f'   set -g menu-border-style "fg={s["surface2"]}"\'',
        "",
        "#+--- Hand-off to third-party plugins ---+",
        f'set -gq @prefix_highlight_fg "{s["base"]}"',
        f'set -gq @prefix_highlight_bg "{accent}"',
    ]
    return "\n".join(lines) + "\n"


def _status(v: Variant) -> str:
    s, txt = v.surfaces, v.text
    accent = v.rc("keyword")
    return f"""# {HEADER}
#
# Optional status-line CONTENT for {v.label}. Source this AFTER the theme
# only if you want the layout too:
#   source-file ~/.config/tmux/grafana/{v.id}.conf
#   source-file ~/.config/tmux/grafana/{v.id}-status.conf
#
# Plain ASCII separators, so no patched font is required.

set -g status-left-length 40
set -g status-right-length 80

set -g status-left "#[fg={s['base']},bg={accent},bold] #S #[fg={accent},bg={s['mantle']},nobold] "
set -g status-right "#[fg={txt['faint']}]%Y-%m-%d #[fg={txt['subtext']}]%H:%M #[fg={s['base']},bg={v.rc('function')},bold] #h "

set -g window-status-format " #I #W#{{?window_flags,#{{window_flags}}, }} "
set -g window-status-current-format " #I #W#{{?window_flags,#{{window_flags}}, }} "
set -g window-status-separator ""
"""


def _tpm(p: Palette) -> str:
    return f"""#!/usr/bin/env bash
# {HEADER}
#
# TPM entry point. With
#   set -g @plugin 'ymotongpoo/grafana-color-scheme'
# TPM runs this file, which sources the theme selected by @grafana_variant.
#
#   set -g @grafana_variant 'dark'    # or 'light'
#   set -g @grafana_status  'off'     # 'on' to also take the status layout

set -euo pipefail

DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"

variant="$(tmux show-option -gqv '@grafana_variant')"
[ -n "$variant" ] || variant="dark"
case "$variant" in
  dark|light) ;;
  *)
    tmux display-message "grafana-color-scheme: unknown @grafana_variant '$variant', using dark"
    variant="dark"
    ;;
esac

tmux source-file "$DIR/src/grafana-$variant.conf"

status="$(tmux show-option -gqv '@grafana_status')"
if [ "$status" = "on" ]; then
  tmux source-file "$DIR/src/grafana-$variant-status.conf"
fi
"""


def emit(p: Palette) -> dict[str, str]:
    files: dict[str, str] = {"grafana.tmux": _tpm(p)}
    for _name, v in p.each():
        files[f"src/{v.id}.conf"] = _theme(v)
        files[f"src/{v.id}-status.conf"] = _status(v)
    return files
