"""Vim and Neovim colorschemes.

Both guifg/guibg and ctermfg/ctermbg are defined so the scheme works with or
without truecolor. `set termguicolors` is deliberately NOT called from here:
it is the user's decision and turning it on unasked breaks plain Vim inside
tmux. The README says what to add.

Neovim's treesitter captures and Diagnostic* groups are covered in the same
vimscript file, so no Lua module is needed to get a current-looking Neovim.
"""

from __future__ import annotations

from ..palette import Palette, Variant

HEADER = "Generated by tools/generate.py from palette.toml. Do not edit."

# cterm indices for the 16 ANSI slots, so a 16-color terminal still tracks
# the same role assignment as the truecolor palette.
_CTERM = {
    "surface1": "236",
    "surface0": "235",
    "surface2": "238",
    "base": "234",
    "mantle": "233",
    "crust": "232",
    "fg": "252",
    "bright": "255",
    "subtext": "246",
    "faint": "245",
    "orange": "173",
    "amber": "179",
    "yellow": "143",
    "green": "107",
    "light-green": "72",
    "light-blue": "73",
    "blue": "110",
    "indigo": "104",
    "purple": "176",
    "pink": "168",
}
_CTERM_LIGHT = {
    "surface1": "253",
    "surface0": "255",
    "surface2": "251",
    "base": "255",
    "mantle": "254",
    "crust": "252",
    "fg": "238",
    "bright": "233",
    "subtext": "240",
    "faint": "242",
    "orange": "topaz",  # replaced below; placeholder never used
}


def _cterm_map(v: Variant) -> dict[str, str]:
    if v.is_dark:
        return _CTERM
    return {
        "surface1": "253",
        "surface0": "255",
        "surface2": "251",
        "base": "255",
        "mantle": "254",
        "crust": "252",
        "fg": "238",
        "bright": "233",
        "subtext": "240",
        "faint": "242",
        "orange": "124",
        "amber": "94",
        "yellow": "58",
        "green": "29",
        "light-green": "23",
        "light-blue": "24",
        "blue": "20",
        "indigo": "61",
        "purple": "127",
        "pink": "125",
    }


def _theme(p: Palette, v: Variant) -> str:
    cterm = _cterm_map(v)
    tokens: dict[str, tuple[str, str]] = {}
    for name, hexv in {**v.surfaces, **v.text, **v.accents}.items():
        tokens[name] = (hexv, cterm.get(name, "NONE"))

    lines: list[str] = [
        f'" {v.id}.vim -- {v.label}',
        f'" {HEADER}',
        f'" {p.scheme["homepage"]}',
        f'" SPDX-License-Identifier: {p.scheme["license"]}',
        '"',
        '" Truecolor is not enabled here on purpose. Add to your own config:',
        '"   set termguicolors',
        '" and inside tmux (3.2+):',
        '"   set -as terminal-features ",*:RGB"',
        "",
        "highlight clear",
        "if exists('syntax_on')",
        "  syntax reset",
        "endif",
        "",
        f"set background={v.appearance}",
        f"let g:colors_name = '{v.id}'",
        "",
        '" Opt out of italics if your terminal renders them as reverse video.',
        "let s:italic = get(g:, 'grafana_italic', 1) ? 'italic' : 'NONE'",
        "let s:bold = get(g:, 'grafana_bold', 1) ? 'bold' : 'NONE'",
        "",
        '" Palette: [gui, cterm]',
    ]
    width = max(len(k) for k in tokens)
    for name, (hexv, ct) in tokens.items():
        var = name.replace("-", "_")
        lines.append(f"let s:{var.ljust(width)} = ['{hexv}', '{ct}']")
    lines += [
        "let s:none = ['NONE', 'NONE']",
        "",
        "function! s:hi(group, fg, bg, attr, sp) abort",
        "  let l:cmd = 'highlight ' . a:group",
        "  let l:cmd .= ' guifg=' . a:fg[0] . ' ctermfg=' . a:fg[1]",
        "  let l:cmd .= ' guibg=' . a:bg[0] . ' ctermbg=' . a:bg[1]",
        '  let l:cmd .= " gui=" . a:attr',
        '  " undercurl is unavailable in most terminals; fall back to underline.',
        "  let l:cmd .= ' cterm=' . substitute(a:attr, 'undercurl', 'underline', 'g')",
        "  if a:sp !=# ''",
        "    let l:cmd .= ' guisp=' . a:sp",
        "  endif",
        "  execute l:cmd",
        "endfunction",
        "",
    ]

    def s(name: str) -> str:
        return "s:" + name.replace("-", "_")

    r = lambda role: s(v.role(role).token)  # noqa: E731
    err = s(v.diagnostic["error"].token)
    warn = s(v.diagnostic["warning"].token)
    info = s(v.diagnostic["info"].token)
    ok = s(v.diagnostic["ok"].token)
    added = s(v.diff["added"].token)
    removed = s(v.diff["removed"].token)
    changed = s(v.diff["changed"].token)

    groups: list[tuple[str, str, str, str, str]] = [
        # (group, fg, bg, attr, sp)
        ("Normal", "s:fg", "s:base", "NONE", ""),
        ("NormalNC", "s:fg", "s:base", "NONE", ""),
        ("NormalFloat", "s:fg", "s:mantle", "NONE", ""),
        ("FloatBorder", "s:surface2", "s:mantle", "NONE", ""),
        ("FloatTitle", r("heading"), "s:mantle", "s:bold", ""),
        ("Cursor", "s:base", r("keyword"), "NONE", ""),
        ("lCursor", "s:base", r("keyword"), "NONE", ""),
        ("CursorLine", "s:none", "s:surface0", "NONE", ""),
        ("CursorColumn", "s:none", "s:surface0", "NONE", ""),
        ("CursorLineNr", "s:fg", "s:surface0", "s:bold", ""),
        ("LineNr", "s:faint", "s:none", "NONE", ""),
        ("LineNrAbove", "s:faint", "s:none", "NONE", ""),
        ("LineNrBelow", "s:faint", "s:none", "NONE", ""),
        ("SignColumn", "s:faint", "s:none", "NONE", ""),
        ("FoldColumn", "s:faint", "s:none", "NONE", ""),
        ("Folded", "s:subtext", "s:surface0", "NONE", ""),
        ("ColorColumn", "s:none", "s:surface0", "NONE", ""),
        ("Visual", "s:none", "s:surface1", "NONE", ""),
        ("VisualNOS", "s:none", "s:surface1", "NONE", ""),
        ("Search", "s:base", warn, "NONE", ""),
        ("IncSearch", "s:base", r("keyword"), "NONE", ""),
        ("CurSearch", "s:base", r("keyword"), "s:bold", ""),
        ("Substitute", "s:base", r("regex"), "NONE", ""),
        ("MatchParen", r("function"), "s:surface1", "s:bold", ""),
        ("NonText", "s:surface2", "s:none", "NONE", ""),
        ("Whitespace", "s:surface2", "s:none", "NONE", ""),
        ("SpecialKey", "s:surface2", "s:none", "NONE", ""),
        ("EndOfBuffer", "s:surface1", "s:none", "NONE", ""),
        ("Conceal", "s:faint", "s:none", "NONE", ""),
        ("Directory", r("type"), "s:none", "s:bold", ""),
        ("Title", r("heading"), "s:none", "s:bold", ""),
        ("ErrorMsg", err, "s:none", "s:bold", ""),
        ("WarningMsg", warn, "s:none", "NONE", ""),
        ("ModeMsg", "s:fg", "s:none", "s:bold", ""),
        ("MoreMsg", ok, "s:none", "NONE", ""),
        ("Question", r("keyword"), "s:none", "NONE", ""),
        ("MsgArea", "s:fg", "s:none", "NONE", ""),
        ("MsgSeparator", "s:surface1", "s:none", "NONE", ""),
        ("StatusLine", "s:fg", "s:surface0", "NONE", ""),
        ("StatusLineNC", "s:faint", "s:mantle", "NONE", ""),
        ("WinBar", "s:fg", "s:none", "s:bold", ""),
        ("WinBarNC", "s:faint", "s:none", "NONE", ""),
        ("VertSplit", "s:surface1", "s:none", "NONE", ""),
        ("WinSeparator", "s:surface1", "s:none", "NONE", ""),
        ("TabLine", "s:faint", "s:mantle", "NONE", ""),
        ("TabLineFill", "s:none", "s:crust", "NONE", ""),
        ("TabLineSel", "s:bright", "s:base", "s:bold", ""),
        ("Pmenu", "s:fg", "s:mantle", "NONE", ""),
        ("PmenuSel", "s:bright", "s:surface1", "s:bold", ""),
        ("PmenuSbar", "s:none", "s:surface0", "NONE", ""),
        ("PmenuThumb", "s:none", "s:surface2", "NONE", ""),
        ("PmenuKind", r("type"), "s:mantle", "NONE", ""),
        ("PmenuExtra", "s:faint", "s:mantle", "NONE", ""),
        ("WildMenu", "s:base", r("keyword"), "NONE", ""),
        ("QuickFixLine", "s:none", "s:surface1", "NONE", ""),
        ("SpellBad", "s:none", "s:none", "undercurl", f"{err}[0]"),
        ("SpellCap", "s:none", "s:none", "undercurl", f"{warn}[0]"),
        ("SpellRare", "s:none", "s:none", "undercurl", f"{info}[0]"),
        ("SpellLocal", "s:none", "s:none", "undercurl", f"{info}[0]"),
        ("DiffAdd", added, "s:none", "NONE", ""),
        ("DiffChange", changed, "s:none", "NONE", ""),
        ("DiffDelete", removed, "s:none", "NONE", ""),
        ("DiffText", "s:base", changed, "NONE", ""),
        ("Added", added, "s:none", "NONE", ""),
        ("Changed", changed, "s:none", "NONE", ""),
        ("Removed", removed, "s:none", "NONE", ""),
        # Syntax groups
        ("Comment", r("comment"), "s:none", "s:italic", ""),
        ("Constant", r("constant"), "s:none", "NONE", ""),
        ("String", r("string"), "s:none", "NONE", ""),
        ("Character", r("string"), "s:none", "NONE", ""),
        ("Number", r("number"), "s:none", "NONE", ""),
        ("Float", r("number"), "s:none", "NONE", ""),
        ("Boolean", r("boolean"), "s:none", "NONE", ""),
        ("Identifier", r("variable"), "s:none", "NONE", ""),
        ("Function", r("function"), "s:none", "NONE", ""),
        ("Statement", r("keyword"), "s:none", "NONE", ""),
        ("Conditional", r("keyword-ctrl"), "s:none", "NONE", ""),
        ("Repeat", r("keyword-ctrl"), "s:none", "NONE", ""),
        ("Label", r("label"), "s:none", "NONE", ""),
        ("Operator", r("operator"), "s:none", "NONE", ""),
        ("Keyword", r("keyword"), "s:none", "NONE", ""),
        ("Exception", r("keyword-ctrl"), "s:none", "NONE", ""),
        ("PreProc", r("preprocessor"), "s:none", "NONE", ""),
        ("Include", r("preprocessor"), "s:none", "NONE", ""),
        ("Define", r("preprocessor"), "s:none", "NONE", ""),
        ("Macro", r("preprocessor"), "s:none", "NONE", ""),
        ("PreCondit", r("preprocessor"), "s:none", "NONE", ""),
        ("Type", r("type"), "s:none", "NONE", ""),
        ("StorageClass", r("keyword"), "s:none", "NONE", ""),
        ("Structure", r("class"), "s:none", "NONE", ""),
        ("Typedef", r("type"), "s:none", "NONE", ""),
        ("Special", r("string-escape"), "s:none", "NONE", ""),
        ("SpecialChar", r("string-escape"), "s:none", "NONE", ""),
        ("Tag", r("tag"), "s:none", "NONE", ""),
        ("Delimiter", r("punctuation"), "s:none", "NONE", ""),
        ("SpecialComment", r("comment-doc"), "s:none", "s:italic", ""),
        ("Debug", warn, "s:none", "NONE", ""),
        ("Underlined", r("link"), "s:none", "underline", ""),
        ("Bold", "s:none", "s:none", "s:bold", ""),
        ("Italic", "s:none", "s:none", "s:italic", ""),
        ("Ignore", "s:faint", "s:none", "NONE", ""),
        ("Error", err, "s:none", "NONE", ""),
        ("Todo", r("keyword"), "s:surface0", "s:bold", ""),
        # Neovim diagnostics
        ("DiagnosticError", err, "s:none", "NONE", ""),
        ("DiagnosticWarn", warn, "s:none", "NONE", ""),
        ("DiagnosticInfo", info, "s:none", "NONE", ""),
        ("DiagnosticHint", "s:subtext", "s:none", "NONE", ""),
        ("DiagnosticOk", ok, "s:none", "NONE", ""),
        ("DiagnosticUnderlineError", "s:none", "s:none", "undercurl", f"{err}[0]"),
        ("DiagnosticUnderlineWarn", "s:none", "s:none", "undercurl", f"{warn}[0]"),
        ("DiagnosticUnderlineInfo", "s:none", "s:none", "undercurl", f"{info}[0]"),
        ("DiagnosticUnderlineHint", "s:none", "s:none", "undercurl", "s:subtext[0]"),
        ("LspReferenceText", "s:none", "s:surface1", "NONE", ""),
        ("LspReferenceRead", "s:none", "s:surface1", "NONE", ""),
        ("LspReferenceWrite", "s:none", "s:surface1", "NONE", ""),
        ("LspSignatureActiveParameter", r("parameter"), "s:none", "s:bold", ""),
        ("LspInlayHint", "s:faint", "s:none", "s:italic", ""),
    ]

    for group, fg, bg, attr, sp in groups:
        attr_expr = attr if attr.startswith("s:") else f"'{attr}'"
        sp_expr = f"{sp}" if sp else "''"
        lines.append(f"call s:hi('{group}', {fg}, {bg}, {attr_expr}, {sp_expr})")

    # Treesitter captures, expressed as links where a classic group already
    # carries the right color, and directly where it does not.
    ts_direct: list[tuple[str, str]] = [
        ("@comment", r("comment")),
        ("@comment.documentation", r("comment-doc")),
        ("@string", r("string")),
        ("@string.documentation", r("comment-doc")),
        ("@string.escape", r("string-escape")),
        ("@string.regexp", r("regex")),
        ("@string.special", r("string-escape")),
        ("@character", r("string")),
        ("@number", r("number")),
        ("@number.float", r("number")),
        ("@boolean", r("boolean")),
        ("@constant", r("constant")),
        ("@constant.builtin", r("builtin")),
        ("@constant.macro", r("preprocessor")),
        ("@function", r("function")),
        ("@function.builtin", r("builtin")),
        ("@function.call", r("function")),
        ("@function.method", r("method")),
        ("@function.method.call", r("method")),
        ("@function.macro", r("preprocessor")),
        ("@constructor", r("class")),
        ("@keyword", r("keyword")),
        ("@keyword.conditional", r("keyword-ctrl")),
        ("@keyword.repeat", r("keyword-ctrl")),
        ("@keyword.return", r("keyword-ctrl")),
        ("@keyword.exception", r("keyword-ctrl")),
        ("@keyword.import", r("preprocessor")),
        ("@keyword.operator", r("keyword-op")),
        ("@keyword.function", r("keyword")),
        ("@keyword.type", r("keyword")),
        ("@keyword.modifier", r("keyword")),
        ("@keyword.directive", r("preprocessor")),
        ("@type", r("type")),
        ("@type.builtin", r("builtin")),
        ("@type.definition", r("type")),
        ("@attribute", r("attribute")),
        ("@property", r("property")),
        ("@variable", r("variable")),
        ("@variable.builtin", r("builtin")),
        ("@variable.member", r("property")),
        ("@variable.parameter", r("parameter")),
        ("@module", r("namespace")),
        ("@label", r("label")),
        ("@operator", r("operator")),
        ("@punctuation.bracket", r("punctuation")),
        ("@punctuation.delimiter", r("punctuation")),
        ("@punctuation.special", r("string-escape")),
        ("@tag", r("tag")),
        ("@tag.attribute", r("attribute")),
        ("@tag.delimiter", r("punctuation")),
        ("@markup.raw", r("string")),
        ("@markup.link", r("link")),
        ("@markup.list", r("keyword")),
        ("@diff.plus", added),
        ("@diff.minus", removed),
        ("@diff.delta", changed),
    ]
    lines += ["", '" Treesitter captures (Neovim)']
    for group, token in ts_direct:
        lines.append(f"call s:hi('{group}', {token}, s:none, 'NONE', '')")
    lines += [
        f"call s:hi('@markup.heading', {r('heading')}, s:none, s:bold, '')",
        "call s:hi('@markup.strong', s:none, s:none, s:bold, '')",
        "call s:hi('@markup.italic', s:none, s:none, s:italic, '')",
        f"call s:hi('@markup.strikethrough', {s('faint')}, s:none, 'strikethrough', '')",
        f"call s:hi('@comment.error', {err}, s:none, 'NONE', '')",
        f"call s:hi('@comment.warning', {warn}, s:none, 'NONE', '')",
        f"call s:hi('@comment.todo', {r('keyword')}, s:surface0, s:bold, '')",
        f"call s:hi('@comment.note', {info}, s:none, 'NONE', '')",
    ]

    ansi = v.ansi("dim")
    lines += [
        "",
        '" Terminal palette',
        "let g:terminal_ansi_colors = [",
    ]
    for i in range(0, 16, 4):
        row = ", ".join(f"'{ansi[j]}'" for j in range(i, i + 4))
        comma = "," if i + 4 < 16 else ""
        lines.append(f"      \\ {row}{comma}")
    lines.append("      \\ ]")
    lines += ["if has('nvim')"]
    for i in range(16):
        lines.append(f"  let g:terminal_color_{i} = '{ansi[i]}'")
    lines.append("endif")
    lines.append("")
    lines.append("delfunction s:hi")
    return "\n".join(lines) + "\n"


def emit(p: Palette) -> dict[str, str]:
    return {f"colors/{v.id}.vim": _theme(p, v) for _n, v in p.each()}
