"""WezTerm color schemes.

TOML rather than Lua on purpose: WezTerm's own docs recommend it for shared
schemes because a TOML file carries no executable logic. Drop these in
~/.config/wezterm/colors/ and no config change is needed to make them
selectable.

Two shapes to watch: [metadata] is a SIBLING of [colors], not nested inside
it, and the copy_mode / quick_select keys take a tagged { Color = "..." }
value rather than a bare string.
"""

from __future__ import annotations

from ..palette import Palette, Variant

HEADER = "Generated by tools/generate.py from palette.toml. Do not edit."


def _scheme(p: Palette, v: Variant, flavor: str) -> str:
    ansi = v.ansi(flavor)
    t = v.terminal
    label = v.label + (" Vivid" if flavor == "vivid" else "")
    normal = ", ".join(f'"{ansi[i]}"' for i in range(8))
    bright = ", ".join(f'"{ansi[i]}"' for i in range(8, 16))

    return f"""# {HEADER}
#
# {label}
# Copy to ~/.config/wezterm/colors/ then set in wezterm.lua:
#   config.color_scheme = "{label}"

[metadata]
name = "{label}"
author = "{p.scheme['author']}"
origin_url = "{p.scheme['homepage']}"

[colors]
foreground = "{v.text['fg']}"
background = "{v.surfaces['base']}"

cursor_bg = "{t['cursor_bg']}"
cursor_fg = "{t['cursor_fg']}"
cursor_border = "{t['cursor_bg']}"

selection_bg = "{t['selection_bg']}"
selection_fg = "{t['selection_fg']}"

scrollbar_thumb = "{v.surfaces['surface1']}"
split = "{t['split']}"
compose_cursor = "{v.rc('builtin')}"

# 0-7: black red green yellow blue magenta cyan white
ansi = [{normal}]
# 8-15: the bright variants
brights = [{bright}]

# Palette slots 16-255 are left to the terminal's own cube.
[colors.indexed]

copy_mode_active_highlight_bg = {{ Color = "{v.rc('builtin')}" }}
copy_mode_active_highlight_fg = {{ Color = "{v.surfaces['base']}" }}
copy_mode_inactive_highlight_bg = {{ Color = "{v.surfaces['surface1']}" }}
copy_mode_inactive_highlight_fg = {{ Color = "{v.text['fg']}" }}
quick_select_label_bg = {{ Color = "{v.rc('keyword')}" }}
quick_select_label_fg = {{ Color = "{v.surfaces['base']}" }}
quick_select_match_bg = {{ Color = "{v.rc('function')}" }}
quick_select_match_fg = {{ Color = "{v.surfaces['base']}" }}

[colors.tab_bar]
background = "{v.surfaces['crust']}"
inactive_tab_edge = "{v.surfaces['surface1']}"

[colors.tab_bar.active_tab]
bg_color = "{v.surfaces['base']}"
fg_color = "{v.text['bright']}"
intensity = "Normal"
underline = "None"
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab]
bg_color = "{v.surfaces['mantle']}"
fg_color = "{v.text['faint']}"

[colors.tab_bar.inactive_tab_hover]
bg_color = "{v.surfaces['surface0']}"
fg_color = "{v.text['fg']}"
italic = true

[colors.tab_bar.new_tab]
bg_color = "{v.surfaces['mantle']}"
fg_color = "{v.text['faint']}"

[colors.tab_bar.new_tab_hover]
bg_color = "{v.surfaces['surface0']}"
fg_color = "{v.text['bright']}"
italic = true
"""


def emit(p: Palette) -> dict[str, str]:
    files: dict[str, str] = {}
    for _name, v in p.each():
        for flavor in p.flavors:
            suffix = "" if flavor == p.scheme["default_flavor"] else f"-{flavor}"
            files[f"colors/{v.id}{suffix}.toml"] = _scheme(p, v, flavor)
    return files
